import Head from 'next/head';
import styles from '../../styles/Layout.module.css'
import Header from './Header';

const Layout = () => {
    return (
    <div className={styles.container}>
        <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        
            <main className={styles.main}>
            <Header></Header>
        
        </main>

        <footer className={styles.footer}></footer>
    </div>
    );
};

export default Layout;